### ISSUE TITLE
Unable to compare some documents

### ISSUE THREAD

**Issue by adrianeboyd** [adrianeboyd/feat#10]
Some pairs of documents cannot be opened for comparison. Details to come.

**Comment by adrianeboyd** [comment]
Something is going wrong when there's b annotation in one file and not the other (even if the b annotation is partially there in the other), but I still don't understand exactly what's going on.

The errors look like:

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at org.purl.jh.util.col.List2D.addEmptyColumn(List2D.java:76)
	at org.purl.jh.feat.diffui.SyncLayout.sync(SyncLayout.java:77)
	at org.purl.jh.feat.diffui.SyncLayout.go(SyncLayout.java:58)
	at org.purl.jh.feat.diffui.DiffPanel.showParaGraph(DiffPanel.java:576)
	at org.purl.jh.feat.diffui.DiffPanel.requestPara(DiffPanel.java:531)
	at org.purl.jh.feat.diffui.DiffPanel.<init>(DiffPanel.java:180)
	at org.purl.jh.feat.diffui.api.Api.openDiff(Api.java:28)
```

or

```
java.lang.NullPointerException
	at org.purl.jh.feat.diffui.diff.FormEd$Matcher.getOps(FormEd.java:169)
	at org.purl.jh.feat.diffui.diff.Diff3.matchForms(Diff3.java:195)
	at org.purl.jh.feat.diffui.diff.Diff3.matchAndDiffPara(Diff3.java:179)
	at org.purl.jh.feat.diffui.diff.Diff3.matchAndDiffLayer(Diff3.java:166)
	at org.purl.jh.feat.diffui.diff.Diff3.calculateDiff(Diff3.java:78)
	at org.purl.jh.feat.diffui.DiffPanel.ensureMatching(DiffPanel.java:351)
	at org.purl.jh.feat.diffui.DiffPanel.highlightCurPara(DiffPanel.java:388)
	at org.purl.jh.feat.diffui.DiffPanel.requestPara(DiffPanel.java:532)
	at org.purl.jh.feat.diffui.DiffPanel.<init>(DiffPanel.java:180)
[catch] at org.purl.jh.feat.diffui.api.Api.openDiff(Api.java:29)
	at org.purl.jh.feat.diffui.OpenFolderDiffAction.actionPerformed(OpenFolderDiffAction.java:62)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
